### ISSUE TITLE
Possible fix for firebase___default.a is not a function

### ISSUE THREAD

**Issue by Morganjackson** [kieusonlam/vue-feathers-wepack#1]
@kieusonlam great start on the starter project! 

 I found your issue https://github.com/vuejs/vue-hackernews-2.0/issues/51 while looking for a solution to the same error. I downgraded firebase to `"firebase": "^2.4.2",` which seems to have fixed it but now I'm seeing this:

`TypeError: Cannot read property 'path' of undefined`

**Comment by Morganjackson** [comment]
Installing `vuex-router-sync@next` fixes the routing issue.

**Comment by kieusonlam** [comment]
Thanks you for your help. The problem is  solved.
