### ISSUE TITLE
Implementation without Firebase

### ISSUE THREAD

**Issue by chuyik** [kieusonlam/vue-feathers-wepack#2]
Hi there, thanks for your work, I love the feathers integration.
But I find that you still rely on Firebase, so what's the point to use feathers?

**Comment by Morganjackson** [comment]
The firebase stuff is just from https://github.com/vuejs/vue-hackernews-2.0

To see the feathers integration look in the [homeView](https://github.com/kieusonlam/vue-feathers-wepack/blob/master/client/views/HomeView.vue) and [post service](https://github.com/kieusonlam/vue-feathers-wepack/tree/master/src/services/post)

**Comment by chuyik** [comment]
@Morganjackson Yes I know, but I'm wondering how to do the pagination with feathers?
I noticed that the `vue-hackernews-2.0` try to fetch all item ids first, and then load item for each if it is not fetched or cached.
But what if I fetch the necessary items instead of fetching all ids first? Can I still find a way to cache them and paginate with them?

Sorry I don't know if I make it clear, but I'm just wondering about the structure.

**Comment by kieusonlam** [comment]
@chuyik I removed firebase and every thing related with it. I start this project to learn so I'm not quite sure what I'm going to do about that stuff yet. But I'm working on it and sure if I figured it out I will commit it.

**Comment by ram-you** [comment]
Hi @chuyik
Can we rely on your project ? You still working on it ?
Have you a working demo link ?
Thanks in advance for response.

**Comment by chuyik** [comment]
@ram-you I'm afraid you are referring to a wrong person, I'm not a maintainer of this project.

**Comment by kieusonlam** [comment]
@ram-you I did have demo link. If you have node js and mongodb ready on your computer. You can just download its and try it.
```
# serve in dev mode, with hot reload at localhost:3030
npm run dev

# build for production
npm run build

# serve in production mode
npm start
```
This project did remove Firebase and I'm using feathers js on server side, you can
- Sign up
- Login
- Logout
- Create post
- Authentication is required to create new post
- Pagination
- Single Post Page
UX might be pretty bad, but everything seem to be work.
