### ISSUE TITLE
Feathers: populate(target, options)  DEPRECATED

### ISSUE THREAD

**Issue by ram-you** [kieusonlam/vue-feathers-wepack#4]
Warning message :

> Calling populate(target, options) is now DEPRECATED and will be removed in the future. Refer to docs.feathersjs.com for more information. (legacyPopulate)

**Comment by kieusonlam** [comment]
Hi @ram-you 

I just fixed it. You can take a look my lastest commit https://github.com/kieusonlam/vue-feathers-wepack/commit/f87477d3574b337370b39bc39db8a1a37a93584a

If you want to know more about feathers populate hook check this link out https://docs.feathersjs.com/v/auk/api/hooks-common.html#populate

I hope this will help you.

**Comment by ram-you** [comment]
Very cool thank you!
